'use strict';
const $=id=>document.getElementById(id),video=document.querySelector('video'),canvas=$('composition'),g=canvas.getContext('2d');let frame,config,stream,front=true,busy=false,ready=false,shots=[],blob,url,filename,runId=0,lastPaint=0;
function controls(){for(const id of['shoot','switch','back','retake','start','captureSettings'])$(id).disabled=busy;$('shoot').disabled=busy||!ready||!frame;const partial=!!config&&shots.length>0&&shots.length<config.boxes.length;if(partial)$('retake').hidden=false;$('retake').textContent=partial?'เริ่มชุดใหม่':'ถ่ายใหม่';$('shoot').textContent=shots.length===config?.boxes.length?'บันทึกชุดภาพ':(config?.boxes.length===3&&CaptureSettings.get().mode==='manual'?`ถ่ายช่องที่ ${Math.min(shots.length+1,3)} / 3`:'ถ่ายภาพ');}
function status(t){$('status').textContent=t;}
function nextRatio(){const b=config.boxes[Math.min(shots.length,config.boxes.length-1)];document.querySelector('.live').style.setProperty('--shot-ratio',b[2]/b[3]);fitPreview();}
function compose(live=true){if(!frame)return;g.fillStyle='#162d3d';g.fillRect(0,0,canvas.width,canvas.height);config.boxes.forEach((b,i)=>{if(shots[i])cover(g,shots[i],b);else if(live&&i===shots.length&&ready&&video.videoWidth)cover(g,video,b,front);});g.drawImage(frame,0,0);}
function animate(now){if(now-lastPaint>33&&!$('booth').hidden&&$('result').hidden){compose();lastPaint=now;}requestAnimationFrame(animate);}requestAnimationFrame(animate);
async function select(c){if(busy)return;busy=true;controls();let loaded=false;const camera=ensureCamera().then(()=>null,e=>e);try{const img=new Image();img.src=c.id+'.png';await img.decode();config=c;frame=prepareFrame(img,c);canvas.width=frame.width;canvas.height=frame.height;reset();$('selection').hidden=true;$('booth').hidden=false;fitPreview();loaded=true;status('กำลังเปิดกล้อง…');const error=await camera;if(error)throw error;status(`พร้อมถ่าย ${config.boxes.length} รูป`);}catch(_){if(loaded){$('start').hidden=false;status('เปิดกล้องไม่ได้ ตรวจสิทธิ์และสายเชื่อมต่อ หรือกดเลือกกล้อง');}else{await camera;stop();$('uploadStatus').textContent='โหลดเฟรมไม่สำเร็จ กรุณาลองใหม่';}}finally{busy=false;controls();}}
for(let i=0;i<FRAMES.length;i+=2){const page=document.createElement('div');page.className='framepage';page.setAttribute('role','group');page.setAttribute('aria-label',`เฟรมหน้า ${i/2+1}`);for(const c of FRAMES.slice(i,i+2)){const b=document.createElement('button');b.className='framecard';const img=new Image();img.src=c.id+'.png';img.alt=c.label;const label=document.createElement('span');label.textContent=c.label;b.append(img,label);b.onclick=()=>select(c);page.append(b);}$('frames').append(page);}
function updatePager(){const page=Math.round($('frames').scrollLeft/Math.max(1,$('frames').clientWidth));$('pageNumber').textContent=`${page+1} / ${Math.ceil(FRAMES.length/2)}`;$('previousPage').disabled=page===0;$('nextPage').disabled=page>=Math.ceil(FRAMES.length/2)-1;}
$('frames').addEventListener('scroll',updatePager,{passive:true});$('previousPage').onclick=()=>$('frames').scrollBy({left:-$('frames').clientWidth,behavior:'smooth'});$('nextPage').onclick=()=>$('frames').scrollBy({left:$('frames').clientWidth,behavior:'smooth'});updatePager();
async function ensureCamera(){if(stream?.getVideoTracks().some(t=>t.readyState==='live')){video.srcObject=stream;await video.play();ready=true;$('start').hidden=true;return;}stream=await navigator.mediaDevices.getUserMedia(CameraSource.constraints(front));video.srcObject=stream;await video.play();const facing=stream.getVideoTracks()[0].getSettings().facingMode;front=facing==='user';video.style.transform=front?'scaleX(-1)':'none';ready=true;$('start').hidden=true;stream.getVideoTracks()[0].onended=()=>{ready=false;$('start').hidden=false;controls();status('กล้องหยุดทำงาน กดเปิดกล้องอีกครั้ง');};}
function stop(){stream?.getTracks().forEach(t=>t.stop());stream=null;ready=false;video.srcObject=null;$('start').hidden=false;controls();}
async function start(){if(busy)return;busy=true;controls();status('กำลังเปิดกล้อง…');try{await ensureCamera();status(`พร้อมถ่าย ${config.boxes.length} รูป`);}catch(_){ready=false;$('start').hidden=false;status('เปิดกล้องที่เลือกไม่ได้ ตรวจสอบสาย Capture Card หรือกดเลือกกล้องเพื่อลองใหม่');}finally{busy=false;controls();}}
$('start').onclick=()=>{void start();try{const promise=document.documentElement.requestFullscreen?.();promise?.then(()=>screen.orientation?.lock?.('landscape')).catch(()=>{});}catch(_){}};
$('switch').onclick=()=>{if(!busy)void CameraSource.show();};
function reset(){shots=[];blob=null;if(url){URL.revokeObjectURL(url);url=null;}$('result').hidden=true;document.querySelector('.cameraPane').hidden=false;canvas.hidden=false;for(const id of['shoot','switch'])$(id).hidden=false;for(const id of['retake','save'])$(id).hidden=true;nextRatio();compose();controls();}
$('back').onclick=()=>{if(busy)return;runId++;reset();$('selection').hidden=false;$('booth').hidden=true;updatePager();};$('retake').onclick=()=>{if(!busy){reset();status('พร้อมถ่ายชุดใหม่ · ชุดก่อนหน้ายังอยู่ในคิวหรือ Drive');}};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
$('shoot').onclick=async()=>{if(busy||!ready||!frame)return;busy=true;controls();const options=CaptureSettings.get();CaptureSettings.unlock();const id=++runId,end=options.mode==='manual'?Math.min(shots.length+1,config.boxes.length):config.boxes.length;try{for(let i=shots.length;i<end;i++){nextRatio();status(`ภาพที่ ${i+1} / ${config.boxes.length}`);for(let n=options.seconds;n>0;n--){CaptureSettings.tick(n);$('count').textContent=n;await delay(1000);if(id!==runId||document.hidden||!matchMedia('(orientation: landscape)').matches||!ready||!video.videoWidth||stream.getVideoTracks()[0].readyState!=='live'||stream.getVideoTracks()[0].muted)throw Error('interrupted');}$('count').textContent='';if(id!==runId||document.hidden||!matchMedia('(orientation: landscape)').matches||!ready||!video.videoWidth||stream.getVideoTracks()[0].readyState!=='live'||stream.getVideoTracks()[0].muted)throw Error('interrupted');CaptureSettings.shutter();const b=config.boxes[i],shot=document.createElement('canvas');shot.width=b[2];shot.height=b[3];cover(shot.getContext('2d'),video,[0,0,b[2],b[3]],front);shots.push(shot);compose();if(i<end-1){status('เปลี่ยนท่าได้เลย');await delay(700);}}
 if(shots.length<config.boxes.length){nextRatio();status(`ถ่ายแล้ว ${shots.length} / ${config.boxes.length} รูป · กดถ่ายช่องถัดไปเมื่อพร้อม`);return;}
 compose(false);blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.95));if(!blob)throw Error('encode');filename='Retire-'+config.id+'-'+new Date().toISOString().replace(/[:.]/g,'-')+'-'+crypto.randomUUID().slice(0,8)+'.jpg';url=URL.createObjectURL(blob);$('result').src=url;$('result').hidden=false;canvas.hidden=true;for(const x of['shoot','switch'])$(x).hidden=true;for(const x of['retake','save'])$(x).hidden=false;status('ถ่ายครบแล้ว');try{await Drive.enqueue(blob,filename);}catch(_){document.getElementById('uploadStatus').textContent='เก็บคิวไม่ได้ กรุณากดบันทึกภาพก่อนเริ่มชุดใหม่';}
 }catch(_){nextRatio();status(`หยุดถ่าย · เก็บไว้ ${shots.length} รูป กดถ่ายเพื่อทำต่อ หรือเริ่มชุดใหม่`);}finally{$('count').textContent='';busy=false;controls();}};
$('save').onclick=async()=>{if(!blob)return;const file=new File([blob],filename,{type:'image/jpeg'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file]});else{const a=document.createElement('a');a.href=url;a.download=filename;a.click();}}catch(e){if(e.name!=='AbortError')document.getElementById('uploadStatus').textContent='แตะภาพค้างแล้วเลือกบันทึกภาพ';}};
window.addEventListener('pagehide',()=>{runId++;stop();});window.addEventListener('pageshow',()=>{if(!ready&&!$('booth').hidden){$('start').hidden=false;controls();}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});

function fitPreview(){if(!config||!frame)return;const pane=document.querySelector('.cameraPane'),live=document.querySelector('.live'),b=config.boxes[Math.min(shots.length,config.boxes.length-1)],ratio=frame.width/frame.height,w=Math.max(1,Math.min(pane.clientWidth,(pane.clientHeight-50)*ratio));live.style.width=w+'px';live.style.height=(w/ratio)+'px';const count=$('count');count.style.left=(b[0]/frame.width*100)+'%';count.style.top=(b[1]/frame.height*100)+'%';count.style.width=(b[2]/frame.width*100)+'%';count.style.height=(b[3]/frame.height*100)+'%';$('start').style.left=((b[0]+b[2]/2)/frame.width*100)+'%';$('start').style.top=((b[1]+b[3]/2)/frame.height*100)+'%';}
new ResizeObserver(fitPreview).observe(document.querySelector('.cameraPane'));

CaptureSettings.onChange=controls;
