'use strict';
const Drive=(()=>{
 const folder='1x8ZkYi3tFpKCyzw-R-rppZlLQXjP2b2P';let token='',expires=0,running=false,db,libs;
 const el=id=>document.getElementById(id),say=t=>el('uploadStatus').textContent=t;
 const opened=new Promise((resolve,reject)=>{const r=indexedDB.open('king-booth-photos',1);r.onupgradeneeded=()=>r.result.createObjectStore('pending',{keyPath:'id'});r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error);});
 async function transaction(mode,fn){await opened;return new Promise((resolve,reject)=>{const tx=db.transaction('pending',mode),r=fn(tx.objectStore('pending'));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
 const all=()=>transaction('readonly',s=>s.getAll()),put=row=>transaction('readwrite',s=>s.put(row)),remove=id=>transaction('readwrite',s=>s.delete(id));
 async function summary(){try{const rows=await all();say(rows.length?`รอส่ง Google Drive ${rows.length} รูป · เก็บคิวในเครื่องแล้ว`:(token?'Google Drive พร้อมรับภาพ':'Google Drive ยังไม่เชื่อมต่อ'));}catch(_){say('เก็บคิวในเครื่องไม่ได้ กรุณาบันทึกภาพเอง');}}
 function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.append(s);});}
 function loadLibraries(){if(!libs)libs=Promise.all([loadScript('https://accounts.google.com/gsi/client'),loadScript('https://apis.google.com/js/api.js')]).then(()=>new Promise(r=>gapi.load('picker',r))).catch(e=>{libs=null;throw e;});return libs;}
 async function showSetup(){el('settings').showModal();el('connect').disabled=true;try{const c=JSON.parse(localStorage.getItem('king-booth-google')||'{}');for(const k of['clientId','apiKey','projectNumber'])el(k).value=c[k]||'';await loadLibraries();el('connect').disabled=false;el('connectStatus').textContent='';}catch(_){el('connectStatus').textContent='โหลด Google ไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วเปิดหน้านี้ใหม่';}}
 function connect(){const c={};for(const k of['clientId','apiKey','projectNumber'])c[k]=el(k).value.trim();if(!c.clientId.endsWith('.apps.googleusercontent.com')||!c.apiKey||!/^\d+$/.test(c.projectNumber)){el('connectStatus').textContent='กรอกข้อมูล Google Cloud ทั้ง 3 ช่องให้ครบ';return;}try{localStorage.setItem('king-booth-google',JSON.stringify(c));}catch(_){}el('connectStatus').textContent='กำลังเชื่อม Google…';
 google.accounts.oauth2.initTokenClient({client_id:c.clientId,scope:'https://www.googleapis.com/auth/drive.file',error_callback:()=>el('connectStatus').textContent='เปิดหน้าลงชื่อเข้าใช้ไม่สำเร็จ กรุณาลองใหม่',callback:r=>{if(r.error){el('connectStatus').textContent='ไม่ได้รับสิทธิ์ Google Drive';return;}token=r.access_token;expires=Date.now()+Number(r.expires_in)*1000-60000;
 const view=new google.picker.DocsView(google.picker.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);
 new google.picker.PickerBuilder().setDeveloperKey(c.apiKey).setAppId(c.projectNumber).setOAuthToken(token).setOrigin(location.origin).addView(view).setTitle('เลือกโฟลเดอร์ปลายทาง Photobooth').setCallback(async data=>{if(data.action===google.picker.Action.CANCEL){token='';el('settings').showModal();el('connectStatus').textContent='ยังไม่ได้เลือกโฟลเดอร์ปลายทาง';}if(data.action===google.picker.Action.PICKED){if(data.docs[0].id!==folder){token='';el('settings').showModal();el('connectStatus').textContent='กรุณาเลือกโฟลเดอร์เดียวกับลิงก์ปลายทางที่กำหนด';return;}try{const f=await api('/files/'+folder+'?fields=id,mimeType,capabilities(canAddChildren)');if(!f.capabilities?.canAddChildren)throw Error('permission');say('เชื่อม Google Drive แล้ว');await flush();}catch(_){token='';say('บัญชีนี้อัปโหลดลงโฟลเดอร์ไม่ได้ กรุณาตรวจสิทธิ์');}}}).build().setVisible(true);el('settings').close();}}).requestAccessToken({prompt:'consent'});}
 async function api(path,options={}){if(!token||Date.now()>expires){token='';throw Error('auth');}const r=await fetch('https://www.googleapis.com/drive/v3'+path,{...options,headers:{Authorization:'Bearer '+token,...options.headers},signal:AbortSignal.timeout(45000)});if(r.status===401){token='';throw Error('auth');}if(!r.ok)throw Error('drive-'+r.status);return r.json();}
 async function flush(){if(running)return;running=true;try{const rows=await all();if(!rows.length){await summary();return;}if(!token||Date.now()>expires){token='';say(`รอส่ง ${rows.length} รูป · เชื่อม Google Drive เพื่ออัปโหลด`);return;}
 for(const row of rows){say('กำลังอัปโหลด '+row.name);if(!row.driveId){const r=await api('/files/generateIds?count=1&space=drive&type=files');row.driveId=r.ids[0];await put(row);}
 // A retained Drive ID makes retries idempotent even when a response is lost.
 let exists=false;try{await api('/files/'+row.driveId+'?fields=id');exists=true;}catch(e){if(e.message!=='drive-404')throw e;}
 if(!exists){const boundary='booth_'+row.id,meta={id:row.driveId,name:row.name,mimeType:'image/jpeg',parents:[folder]};const body=new Blob(['--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: image/jpeg\r\n\r\n',row.blob,'\r\n--'+boundary+'--'],{type:'multipart/related; boundary='+boundary});const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{Authorization:'Bearer '+token},body,signal:AbortSignal.timeout(60000)});if(r.status===401){token='';throw Error('auth');}if(!r.ok&&r.status!==409)throw Error('upload');if(r.status===409)await api('/files/'+row.driveId+'?fields=id');else{const result=await r.json();if(result.id!==row.driveId)throw Error('response');}}
 await remove(row.id);say('อัปโหลด Google Drive สำเร็จ');}
 if((await all()).length)setTimeout(flush,0);
 }catch(e){say(e.message==='auth'?'สิทธิ์ Google หมดอายุ · เชื่อมใหม่เพื่อส่งรูปที่ค้าง':'อัปโหลดไม่สำเร็จ · เก็บรูปในคิวแล้ว กดส่งรูปที่ค้างเพื่อลองใหม่');}finally{running=false;}}
 async function enqueue(blob,name){const row={id:crypto.randomUUID(),blob,name,createdAt:Date.now()};await put(row);say('เก็บรูปในคิวแล้ว');void flush();}
 el('driveSetup').onclick=showSetup;el('closeSettings').onclick=()=>el('settings').close();el('connect').onclick=connect;el('retry').onclick=()=>token?flush():showSetup();window.addEventListener('online',flush);void summary();
 return{enqueue};
})();
